owner: Wideplink
repo: status

sites:
  - name: Wideplink Website
    url: https://wideplink.com
    icon: https://wideplink.com/favicon.ico
    
  - name: Wideplink Dev API
    url: $W_DEV_API_URL
    headers:
      - "Referer: $W_DEV_API_REFERER"
    icon: https://wideplink.com/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.wideplink.com
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.discordapp.com/attachments/888267281619124224/1007174140530266112/unknown.png
  favicon: https://wideplink.com/favicon.ico
  name: Wideplink Status
  introTitle: "Wideplinkは、プリンでゲーム仲間を募集し、プレイヤー同士を繋ぐ、新たな掲示板サイトです"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Wideplink

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
